language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=2.2.12
  - DJANGO=3.0.6

script:
  - pip install Django==$DJANGO
  - python setup.py test
