language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=1.11.18
  - DJANGO=2.0.10
  - DJANGO=2.1.5

script:
  - pip install Django==$DJANGO
  - python setup.py test
